---
- name: "Restart gitea"
  service:
    name: gitea
    state: restarted
  when: ansible_service_mgr == "systemd"

- name: "Reload systemd"
  systemd:
    daemon_reload: true
  when: ansible_service_mgr == "systemd"

- name: "Restart fail2ban"
  service:
    name: fail2ban
    state: restarted
  when: ansible_service_mgr == "systemd"

- name: "Setup admin"
  command:
    argv:
      - gitea
      - admin
      - create-user
      - -c
      - "{{ gitea_config_path }}"
      - --username
      - "{{ gitea_admin_user }}"
      - --password
      - "{{ gitea_admin_password }}"
      - --email
      - me@example.com
  when: true
